# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

# Sample .travis.yml for R projects.
#
# See README.md for instructions, or for more configuration options,
# see the wiki:
#   https://github.com/craigcitro/r-travis/wiki - deprecated
#   http://jtleek.com/protocols/travis_bioc_devel/ - deprecated

#https://github.com/r-lib/usethis/issues/420
#should use the biocViews: tag in the DESCRIPTION file instead.
#Unsure how to do this, so just see if I can force it for now using the bioc_packages: field below

language: R

r: bioc-release

cache:
  directories:
    - $TRAVIS_BUILD_DIR/packrat/src
    - $TRAVIS_BUILD_DIR/packrat/lib
  packages: true

bioc_packages:
  - Biostrings
  - IRanges
  - Rsamtools
  - GenomicRanges
  - S4Vectors

notifications:
  recipients:
    - jennyl.smith12@gmail.com
  email:
    on_success: change
    on_failure: change

