---
title: "Annotate and Summary Stats of Breakpoint Evidence"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Annotate and Summary Stats of Breakpoint Evidence}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

#Set-up

```{r setup}
knitr::opts_knit$set(
  root.dir = file.path(PROJHOME,"2020.09.15_RNAseq_Fusion_Breakpoints"))

library(fusBreakpoint)
library(magrittr)
library(dplyr)
library(tibble)
library(stringr)
```

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  tidy.opts=list(width.cutoff=50),
  tidy=TRUE, 
  fig.align='center',
  fig.width = 10, 
  fig.height = 10
)
```


#Define Functions

```{r}
#Needs to be build into the package
source(file.path(SCRIPTS,"RNAseq_Analysis/fusBreakpoint/R/survplot_functions.R.bak"))
```

#ClinData

```{r}
merged <- read.csv(file.path(CDE,"Merged/TARGET_AML_0531_1031_merged_CDEs_9.18.20.csv"))



merged <- merged %>%
  filter(!is.na(USI), USI != "Unknown") %>%
  set_rownames(.$USI)

inelig <- c(773920,775026, 786948,799528)
ineligables <- merged %>% 
  filter(Eligibility_Comments == "remove" | Reg. %in% inelig) %>% 
  pull(USI)

dim(merged)
```

```{r}
IDmap <- read.csv("References/St.Jude_TARGET_CICERO_Sample_IDmap.csv")

head(IDmap)
```
 
```{r}
SJCBF <- read.csv("References/SJ_CBF_AML_Clinical_Data.csv") %>% 
  mutate(Sample=str_split_fixed(ID, "\\/", n=2)[,1]) %>% 
  mutate(subject_name=str_split_fixed(Sample,"_", n=2)[,1]) %>%
  select(Sample,subject_name, ID, everything())

head(SJCBF)
dim(SJCBF)
```
 
 
#Read in File Manifests 

```{r}
polyA_RNAseq_files <- read.csv("BAM_Manifests/TARGET_AML_polyA_RNAseq_Bam_Manifest_10.02.20.csv", 
                               row.names = 1) 


dim(polyA_RNAseq_files)
table(duplicated(polyA_RNAseq_files$Sample)) #FALSE
```

```{r}
RBD_RNAseq_files <- read.csv("BAM_Manifests/TARGET_AML_Ribodepleted_RNAseq_Bam_Manifest_10.02.20.csv",row.names = 1)

dim(RBD_RNAseq_files)
table(duplicated(RBD_RNAseq_files$Sample)) #FALSE
```

```{r}
SJ_RNAseq_files <- read.csv("BAM_Manifests/St.Jude_AML_ALL_RNAseq_Bam_Manifest_10.09.20.csv")

dim(SJ_RNAseq_files)
table(duplicated(SJ_RNAseq_files$Sample)) #FALSE
```


#Define the Results files 

```{r}
outdir <- file.path(SCRATCH,'jlsmith3/Fusion_Breakpoints')
outdir
```

```{r}
results_files <- dir(file.path(outdir), 
                 pattern = "results_[01].RDS",
                 recursive = T, 
                 full.names = T)

Names <- str_split_fixed(results_files, "\\/", n=9)[,8] 
Names <- str_split_fixed(Names,"_", n=6)[,3:4]
Names <- paste(as.character(Names[,1]),
               as.character(Names[,2]), sep=".")
names(results_files) <- Names

length(results_files) # 62
head(results_files)
table(names(results_files))
```



#TARGET AML 

```{r}
TARGET_results <- grep("polyA_|RBD_", results_files, value = T)

# table(names(TARGET_results))
length(TARGET_results)
```

```{r eval=FALSE}
cat_results <- lapply(seq(2,length(TARGET_results), by=2), 
                      function(i){

                #select the results files  (in two parts)
                rds0 <- TARGET_results[i-1]
                rds1 <- TARGET_results[i]
                # print(c(rds0,rds1))
                
                #define output filename and destination
                fname <- str_split_fixed(rds0,"\\/", n=9)[,8] %>% 
                  gsub("_rslurm_", "", .) %>% 
                  paste0("TARGET_AML_",., "_breakpoint_evidence.csv")
                
                fusion <- unique(c(names(rds0),names(rds1)))
                print(fusion)
                destination <- paste0(getwd(), "/", fusion, "_Results")
                suppressWarnings(dir.create(destination,recursive = T))
                
                #read in the results
                res <- purrr::map_dfr(c(rds0, rds1), function(x) bind_rows(readRDS(x)))
                
                # RNAseq batch annotations
                if(grepl("polyA", rds0)){
                  res <- res %>%
                      left_join(., select(polyA_RNAseq_files, -filename, -filepath),
                              by="Sample") 
                }else{
                  res <- res %>%
                      left_join(., select(RBD_RNAseq_files, -filename, -filepath),
                                by="Sample") 
                }
                
                #merge in clinical annotations
                res <- res %>%
                     left_join(., select(merged, USI,
                                            matches("OS\\.[tei]|EFS\\.[tei]|Event",ignore.case=FALSE)),
                                  by="USI") %>%
                      select(Sample,USI,Protocol,
                               Primary.Fusion,Additional.Fusions.CNV,
                               Theoretical_Exon_Junctions,
                              Num_Junction_Breakpoint_Reads,
                              Num_RNAseq_Reads_Searched,
                              Lib_Prep:AML_Subtype, everything(),
                             -Reg., -Final_Patient_ID, -PATIENT_ID_Original)
                
                print(paste(destination, fname, sep="/"))
                write.csv(res,paste(destination, fname, sep="/"), row.names = FALSE)
              
              })
```


##CBFB-MYH11

```{r}
cbfb_mut20_RBD <- read.csv("CBFB.MYH11_Results/TARGET_AML_CBFB_MYH11_RBD_RNAseq_mut20_breakpoint_evidence.csv") %>% 
  mutate(Exons=gsub(".+Exons([0-9]_[0-9]{1,2})_.+", "\\1", Theoretical_Exon_Junctions)) %>%
  select(Sample:Additional.Fusions.CNV, Exons,Num_Junction_Breakpoint_Reads, everything())

head(cbfb_mut20_RBD)
length(unique(cbfb_mut20_RBD$Sample)) #1617
table(unique(cbfb_mut20_RBD$USI) %in% cbfb_res_orig$USI) #101 shared 
```

```{r}
cbfb_mut20_polyA <- read.csv("CBFB.MYH11_Results/TARGET_AML_CBFB_MYH11_polyA_RNAseq_mut20_breakpoint_evidence.csv") %>% 
  mutate(Exons=gsub(".+Exons([0-9]_[0-9]{1,2})_.+", "\\1", Theoretical_Exon_Junctions)) %>%
  select(Sample:Additional.Fusions.CNV, Exons,Num_Junction_Breakpoint_Reads, everything())

head(cbfb_mut20_polyA)
length(unique(cbfb_mut20_polyA$Sample)) # 508
table(unique(cbfb_mut20_polyA$USI) %in% cbfb_res_orig$USI) #57 shared 
```

## Check with the original 

```{r}
cbfb_res_orig <- xlsx::read.xlsx("CBFB.MYH11_Results/TARGET_0531_1031.CBFB-MYH11.FusionBreakpoint.Unmasked.xlsx", sheetIndex = 1)

head(cbfb_res_orig)
dim(cbfb_res_orig)#152   4
length(unique(cbfb_res_orig$USI))
```

```{r}
check <- cbfb_mut20_RBD %>% 
  bind_rows(., cbfb_mut20_polyA) %>% 
  inner_join(., cbfb_res_orig, by="USI") %>%
  select(Sample:Exons,Fusion_Breakpoint_Unmasked, Fusion_Breakpoint, everything()) %>%
  filter(Num_Junction_Breakpoint_Reads > 0) %>%
  mutate(Different=ifelse(Exons==Fusion_Breakpoint_Unmasked, "No", "Yes")) %>%
  arrange(desc(Fusion_Breakpoint), Fusion_Breakpoint_Unmasked, USI) %>%
  select(Sample:Additional.Fusions.CNV,Lib_Prep, Different, everything())

table(check$Different, useNA='ifany')
table(duplicated(check$USI))
# write.csv(check,"CBFB_MYH11_Check.csv", row.names = FALSE)
```


## Specificty and Sensitivity

```{r}
inv.16 <- merged %>% 
  filter(!USI %in% ineligables) %>%
  # filter(!is.na(EFS.time..days.)) %>%
  filter(grepl("CBFB-MYH11", Primary.Fusion) | grepl("CBFB-MYH11", Additional.Fusions.CNV)) %>% 
  pull(USI)

length(inv.16)
```

```{r}
cbfb_all <- cbfb_mut20_RBD %>% 
  bind_rows(., cbfb_mut20_polyA)


dim(cbfb_all) #10625    33
length(unique(cbfb_all$Sample)) #1967
head(cbfb_all)
```

```{r}
table(cbfb_res_orig$USI %in% cbfb_all$USI)
# table(unique(cbfb_all$USI) %in% unique(cbfb_res_orig$USI))
New <- setdiff(unique(cbfb_all$USI), unique(cbfb_res_orig$USI))
New <- New[New %in% inv.16]

length(New)
```

```{r}
Filled <- cbfb_all %>% 
  filter(USI %in% New) %>% 
  filter(Num_Junction_Breakpoint_Reads >0)  %>%
  mutate(Breakpoint_Group=ifelse(Exons=="5_33", "A","B")) %>%
  arrange(desc(Breakpoint_Group),USI)

dim(Filled)
any(duplicated(Filled$Sample)) #FALSE
table(Filled$Breakpoint_Group)
```

```{r}
cbf_false_neg <- cbfb_all %>% 
  filter(USI %in% New) %>% 
  group_by(Sample) %>%
  summarise(Any_Read_Evidence=ifelse(any(Num_Junction_Breakpoint_Reads > 0), "Yes", "No")) %>%
  arrange(Any_Read_Evidence,Sample)

table(cbf_false_neg$Any_Read_Evidence)
```

```{r}
FN <- filter(cbf_false_neg, Any_Read_Evidence=="No") %>% 
  pull(Sample) %>%
  str_split_fixed(.,"\\.", n=5) %>%
  .[,3]

knownFP <- merged %>% 
  filter(USI %in% FN) %>%
  select(USI,Primary.CNV, Primary.Fusion, Additional.Fusions.CNV, Cyto.vs..Seq) %>% 
  arrange(Cyto.vs..Seq)

table(knownFP$Cyto.vs..Seq)
```


# ST.Jude Data

```{r}
SJ_results <- grep("_SJ_", results_files, value = T)
# SJresults
table(names(SJ_results))
```

```{r eval=FALSE}
cat_results <- lapply(seq(2,length(SJ_results), by=2), 
                      function(i){

                #select the results files  (in two parts)
                rds0 <- SJ_results[i-1]
                rds1 <- SJ_results[i]
                # print(c(rds0,rds1))
                
                #define output filename and destination
                fname <- str_split_fixed(rds0,"\\/", n=9)[,8] %>% 
                  gsub("_rslurm_", "", .) %>% 
                  paste0("St.Jude_AML_ALL_",., "_breakpoint_evidence.csv")
                
                fusion <- unique(c(names(rds0),names(rds1)))
                print(fusion)
                destination <- paste0(getwd(), "/", fusion, "_Results")
                suppressWarnings(dir.create(destination,recursive = T))
                
                #read in the results
                res <- purrr::map_dfr(c(rds0, rds1), function(x) bind_rows(readRDS(x)))
                
                # RNAseq batch annotations
                if(grepl("polyA", rds0)){
                  res <- res %>%
                      left_join(., select(polyA_RNAseq_files, -filename, -filepath),
                              by="Sample") 
                }else{
                  res <- res %>%
                      left_join(., select(RBD_RNAseq_files, -filename, -filepath),
                                by="Sample") 
                }
                
                #merge in clinical annotations
                res <- res %>%
                     left_join(., select(merged, USI,
                                            matches("OS\\.[tei]|EFS\\.[tei]|Event",ignore.case=FALSE)),
                                  by="USI") %>%
                      select(Sample,USI,Protocol,
                               Primary.Fusion,Additional.Fusions.CNV,
                               Theoretical_Exon_Junctions,
                              Num_Junction_Breakpoint_Reads,
                              Num_RNAseq_Reads_Searched,
                              Lib_Prep:AML_Subtype, everything(),
                             -Reg., -Final_Patient_ID, -PATIENT_ID_Original)
                
                print(paste(destination, fname, sep="/"))
                write.csv(res,paste(destination, fname, sep="/"), row.names = FALSE)
              
})
```

```{r}
star.fmt.primary <- read.csv(file.path("St.Jude_AML_ALL_STAR_Fusion_reformatted_FilteredForNBM_PrimaryFusions_10.12.20.csv"),
                             row.names=FALSE)
```



#Session Information

```{r}
sessionInfo()
```



